export const departments = [
    { "name": "Department of Commerce" },

    { "name": "Department of Defence" },

    { "name": "Department of Expenditure" },

    { "name": "Department of Fertilizers" },

    { "name": "Department of Fisheries" },

    { "name": "Department of Justice" },

    { "name": "Department of Pharmaceuticals" },

    { "name": "Department of Posts" },

    { "name": "Department of Revenue" },

    { "name": "Department of Sports" },

    { "name": "Department of Telecommunications" },

    { "name": "Legislative Department" },

    { "name": "Planning Department" },
    { "name": "Department of Archaeology" },
    { "name": "Department of Space" },

    { "name": "Department of Home" },

    { "name": "Department of States" },

    { "name": "Department of Biotechnology" },

    { "name": "Department of Publication" },
    { "name": "Archaeology Department" },
    { "name": "Department of Tourism" },
    { "name": "Treasury Department" },
    { "name": "Industries Department" },
    { "name": "Health Department" },
    { "name": "Fisheries Department" },
    { "name": "Excise Department" },
    { "name": "Commercial Tax and Excise Department Department" },
    { "name": "Development Department" },
    { "name": "Department of Agriculture" },
    { "name": "Prohibition and Excise Department" },
    { "name": "Agriculture Department" },
    { "name": "Budget Department" },
    { "name": "Election Department" },
    { "name": "Excise Department" },
    { "name": "Forest Department" },
    { "name": "Horticulture Department" },
    { "name": "Labour Department" },
    { "name": "Planning Department" },
    { "name": "Police Department" },
    { "name": "Prison Department" },
    { "name": "Revenue Department" },
    { "name": "Sericulture Department" },
    { "name": "Sports Department" },
    { "name": "Transport Department" },
    { "name": "Forest Department" },
    { "name": "Tourism Department" },
    { "name": "Irrigation Department" },
    { "name": "Tourism Department" },
    { "name": "Vigilance Department" },
    { "name": "Finance Department" },
    { "name": "Transport Department" },
    { "name": "Finance Department" },
    { "name": "Legal Department" },
    { "name": "Revenue Department" },
    { "name": "Tourism Department" },

    { "name": "Election Department" },
    { "name": "Energy Department" },
    { "name": "Agriculture Department" },
    { "name": "Fisheries Department" },
    { "name": "Education Department" },

    { "name": "Fisheries Department" },
    { "name": "Jail Department" },
    { "name": "Tourism Department" },
    { "name": "Labour Department" },
    { "name": "Department of  Prisons" },
    { "name": "Department of Architecture" },
    { "name": "Police Department" },
    { "name": "Registration Department" },
    { "name": "Transport Department" },
    { "name": "Fisheries Department" },
    { "name": "Police Department" },
    { "name": "Finance Department" },
    { "name": "Law Department" },
    { "name": "Transport Department" },
    { "name": "Agriculture Department" },
    { "name": "Finance Department" },
    { "name": "Horticulture Department" },
    { "name": "Prison Department" },
    { "name": "Sericulture Department" },
    { "name": "Tourism Department" },
    { "name": "Vigilance Department" },
    { "name": "Secretariat Administration Department" },
    { "name": "Housing Department" },
    { "name": "Industries Department" },
    { "name": "Labour Department" },
    { "name": "Labour Department" },
    { "name": "Planning Department" },

    { "name": "Energy Department" },
    { "name": "Excise Department" },
    { "name": "Finance Department" },

    { "name": "Industries Department" },
    { "name": "Law Department" },
    { "name": "Works Department" },
    { "name": "Taxes Department" },
    { "name": "Department of Chemicals and Petrochemicals" },

    { "name": "Department of Consumer Affairs" },

    { "name": "Department of Defence Production" },

    { "name": "Department of Economic Affairs" },

    { "name": "Department of Financial Services" },

    { "name": "Department of Health Research" },

    { "name": "Department of Higher Education" },

    { "name": "Department of Legal Affairs" },

    { "name": "Department of Official Language" },

    { "name": "Department of Personnel and Training" },

    { "name": "Department of Public Enterprises" },

    { "name": "Department of Science and Technology" },

    { "name": "Engineering Department" },
    { "name": "Police Department" },
    { "name": "Planning Department" },
    { "name": "Police Department" },
    { "name": "Services Department" },
    { "name": "Agriculture Department" },
    { "name": "Education Department" },
    { "name": "Transport Department" },
    { "name": "Tourism Department" },
    { "name": "Transport Department" },
    { "name": "Vigilance Department" },
    { "name": "Fisheries Department" },
    { "name": "Health Department" },
    { "name": "Irrigation Department" },
    { "name": "Labour Department" },
    { "name": "Lokayukta Department" },
    { "name": "Tourism Department" },
    { "name": "Vigilance Department" },
    { "name": "Education Department" },
    { "name": "Fisheries Department" },
    { "name": "Archaeology Department" },
    { "name": "Forest Department" },
    { "name": "Fisheries Department" },
    { "name": "Taxation Department" },
    { "name": "Finance Department" },
    { "name": "Fisheries Department" },
    { "name": "Home Department" },
    { "name": "Gazetteer Department" },
    { "name": "Harbour Engineering Department " },
    { "name": "Police Department" },
    { "name": "Stationery Department" },
    { "name": "Sainik welfare department " },
    { "name": "Printing department" },
    { "name": "Department of Syrvey" },
    { "name": "Law Department" },
    { "name": "Archaeology Department" },
    { "name": "Forest Department" },

    { "name": "Fisheries Department" },
    { "name": "Taxation Department" },
    { "name": "Department of  Police" },
    { "name": "Taxes Department" },
    { "name": "Department of Taxes" },
    { "name": "Panchayati Raj Department" },
    { "name": "Department of Public Enterprises" },

    { "name": "Department of Science and Technology" },

    { "name": "Department of Youth Affairs" },

    { "name": "Tourism Department" },
    { "name": "Transport Department" },
    { "name": "Tourism Department" },
    { "name": "Police Department" },
    { "name": "Vigilance Department" },
    { "name": "Forest Department" },
    { "name": "Department of Handlooms and Textiles " },
    { "name": "Finance Department" },
    { "name": "Fisheries Department" },
    { "name": "Registration Department" },
    { "name": "Revenue Department" },
    { "name": "Tourism Department" },
    { "name": "Finance Department" },
    { "name": "Irrigation Department" },
    { "name": "Tourism Department" },
    { "name": "Transport Department" },
    { "name": "Finance Department" },
    { "name": "Tourism Department" },
    { "name": "Transport Department" },
    { "name": "AYUSH Department" },
    { "name": "Finance Department" },
    { "name": "Police Department" },
    { "name": "Taxation Department" },
    { "name": "Agriculture Department" },
    { "name": "Transport Department" },
    { "name": "Police Department" },
    { "name": "Excise Department" },
    { "name": "Labour Department" },
    { "name": "Agriculture Department" },
    { "name": "Finance Department" },
    { "name": "Fisheries Department" },

    { "name": "Department of Handlooms and Textiles" },
    { "name": "Department of Treasuries and Accounts" },
    { "name": "Forensic Sciences Department" },
    { "name": "Income Tax Department" },
    { "name": "Department of Electrical Inspectorate" },
    { "name": "Collegiate Education Department" },
    { "name": "Employment Service Department" },
    { "name": "General Education Department" },
    { "name": "Economics and Statistics Department" },
    { "name": "Agricultural Engineering Department" },
    { "name": "Agriculture Department" },
    { "name": "Agriculture Department" },
    { "name": "Environment Department" },
    { "name": "Health Department" },
    { "name": "Industries Department" },
    { "name": "Excise Department" },
    { "name": "Judicial Department" },
    { "name": "Legislative Department" },
    { "name": "Personnel Department" },
    { "name": "Horticulture Department" },
    { "name": "Finance Department" },
    { "name": "Election Department" },
    { "name": "Labour Department" },
    { "name": "Education Department" },
    { "name": "Election Department" },
    { "name": "Personnel Department" },
    { "name": "Vigilance Department" },

    { "name": "Revenue Department" },
    { "name": "Employment Department" },
    { "name": "Revenue Department" },
    { "name": "Environment Department" },
    { "name": "Employment Department" },

    { "name": "Tourism Department" },
    { "name": "Transport Department" },
    { "name": "Personnel Department" },
    { "name": "Finance Department" },
    { "name": "Fisheries Department" },
    { "name": "Housing Department" },
    { "name": "Power Department" },
    { "name": "Industries Department" },
    { "name": "Election Department" },
    { "name": "Welfare Department" },
    { "name": "Energy Department" },
    { "name": "Agriculture Department" },
    { "name": "Revenue Department" },
    { "name": "Industries Department" },
    { "name": "Finance Department" },

    { "name": "Education Department" },
    { "name": "Revenue Department" },
    { "name": "Law Department" },

    { "name": "Irrigation Department" },
    { "name": "Tourism Department" },

    { "name": "Revenue Department" },
    { "name": "Employment Department" },
    { "name": "Elections Department" },
    { "name": "Election Department" },
    { "name": "Education Department" },
    { "name": "Election Department" },
    { "name": "Energy Department" },
    { "name": "Finance Department" },
    { "name": "Planning Department" },
    { "name": "Environment Department" },

    { "name": "Communication Department" },
    { "name": "Political Department" },
    { "name": "Power Department" },
    { "name": "Election Department" },
    { "name": "Election Department" },
    { "name": "Fisheries Department" },
    { "name": "Planning Department" },
    { "name": "Transport Department" },
    { "name": "Revenue Department" },
    { "name": "Finance Department" },
    { "name": "Vigilance Department" },
    { "name": "Agriculture Department" },
    { "name": "Transport Department" },
    { "name": "Industries Department" },

    { "name": "Sericulture Department" },
    { "name": "Police Department" },
    { "name": "Election Department" },
    { "name": "Tourism Department" },
    { "name": "Election Department" },
    { "name": "Personnel Department" },
    { "name": "Power Department" },
    { "name": "Police Department" },
    { "name": "Port Department" },
    { "name": "Prisons Department" },
    { "name": "Tourism Department" },
    { "name": "Transport Department" },
    { "name": "Vigilance Department" },
    { "name": "Housing Department" },
    { "name": "Environment Department" },
    { "name": "Transport Department" },
    { "name": "Transport Department" },
    { "name": "Election Department" },
    { "name": "Energy Department" },

    { "name": "Housing Department" },
    { "name": "Law Department" },
    { "name": "Planning Department" },
    { "name": "Revenue Department" },
    { "name": "Finance Department" },

    { "name": "Finance Department" },
    { "name": "Election Department" },
    { "name": "Police Department" },
    { "name": "Power Department" },
    { "name": "Municipal Administration Department" },
    { "name": "Stores purchase department" },
    { "name": "Labour Department" },
    { "name": "Tourism Department" },
    { "name": "Department of Atomic Energy" },

    { "name": "Water Resources Department" },
    { "name": "Dairy Development Department" },
    { "name": "Transport Department" },
    { "name": "Forest Department" },
    { "name": "Revenue Department" },
    { "name": "Transport Department" },
    { "name": "Finance Department" },
    { "name": "Power Department" },
    { "name": "Tourism Department" },
    { "name": "Cooperation Department" },
    { "name": "Forest Department" },
    { "name": "Gazetteer Department" },
    { "name": "Department of Food & Supplies" },
    { "name": "Revenue Department" },
    { "name": "Employment Department" },
    { "name": "Transport Department" },
    { "name": "Stores purchase department" },
    { "name": "Ground Water Department" },
    { "name": "Agricultural Marketing Department" },
    { "name": "Town planning Department" },
    { "name": "Information Technology Department" },
    { "name": "Technical Education Department" },
    { "name": "Tourism Department" },
    { "name": "Fisheries Department" },
    { "name": "Election Department" },

    { "name": "Tourism Department" },
    { "name": "Marathi Language Department" },
    { "name": "Housing Department" },
    { "name": "Department of Heavy Industry" },

    { "name": "Labour Department" },
    { "name": "Labour Department" },

    { "name": "Tourism Department" },
    { "name": "Agriculture Department" },
    { "name": "Law Department" },
    { "name": "Tourism Department" },
    { "name": "Fisheries Department" },
    { "name": "Forest Department" },
    { "name": "Industry Department" },
    { "name": "Planning Department" },
    { "name": "Police Department" },
    { "name": "Tourism Department" },
    { "name": "Fisheries Department" },
    { "name": "Election Department" },

    { "name": "Tourism Department" },
    { "name": "Revenue Department" },
    { "name": "Employment Department" },
    { "name": "Transport Department" },
    { "name": "Registration Department" },
    { "name": "Sericulture Department" },
    { "name": "Agriculture Department" },
    { "name": "Forests Department" },
    { "name": "Agriculture Department" },
    { "name": "Labour Department" },
    { "name": "Vigilance Department" },
    { "name": "Archives Department" },
    { "name": "Culture Department" },
    { "name": "Department of Industries & Commerce " },
    { "name": "Canteen Stores Departments" },
    { "name": "Finance Department" },
    { "name": "Public Works Department (Building and Roads) and Architecture Department" },
    { "name": "Rural Development Department" },
    { "name": "Environment & Forest Department" },
    { "name": "Energy Department" },
    { "name": "Fisheries Department" },
    { "name": "Labour Department" },
    { "name": "Accounts and Entitlement Department" },
    { "name": "Animal Husbandry Department" },
    { "name": "Co-operative Department" },
    { "name": "Dairy Development Department" },
    { "name": "Employment and Training Department" },
    { "name": "Higher Education Department" },
    { "name": "Information Technology Department" },
    { "name": "Medical Education Department" },
    { "name": "Minority Welfare Department" },
    { "name": "Public Works Department" },
    { "name": "School Education Department" },
    { "name": "Science and Technology Department" },
    { "name": "Stamps and Registration Department" },
    { "name": "Public Works Department" },
    { "name": "Industries and Mines Department" },
    { "name": "Jail Department" },
    { "name": "Urban Development and Environment Department" },
    { "name": "Commerce & Industries Department" },
    { "name": "Culture and Archaeology Department" },
    { "name": "Revenue and Disaster Department" },
    { "name": "Rural Industries Department" },
    { "name": "Science and Technology Department" },
    { "name": "Forests and Environment Department" },
    { "name": "Information and Broadcasting Department" },
    { "name": "Ports and Transport Department" },
    { "name": "Roads and Buildings Department" },
    { "name": "Science and Technology Department" },
    { "name": "Tribal Development Department" },
    { "name": "Technical Education Department" },
    { "name": "Co-operation Department" },
    { "name": "School Education Department" },
    { "name": "Parliamentary Affairs Department" },
    { "name": "Animal Husbandary Department" },
    { "name": "Registration and Stamp Department" },
    { "name": "Water Resources Department" },
    { "name": "Civil Aviation Department" },
    { "name": "General Administration Department" },
    { "name": "Labour and Employment Department" },
    { "name": "Rural Development Department" },
    { "name": "Tourism Department" },
    { "name": "Rehabilitation Department" },
    { "name": "Transport Department" },
    { "name": "Forest Department" },
    { "name": "Rural Development Department" },
    { "name": "State Taxe Department" },
    { "name": "Panchayati Raj Department" },
    { "name": "Sanskrit Education Department" },
    { "name": "Rural Industries Department" },
    { "name": "Higher Education Department" },
    { "name": "Mineral Resource Department" },
    { "name": "Public Relations Department" },
    { "name": "Social Welfare Department" },
    { "name": "Culture Department" },
    { "name": "Revenue Department" },
    { "name": "Social Welfare Department" },
    { "name": "Department of Science" },
    { "name": "Technology and Environment" },
    { "name": "Department of Sainik Welfare" },
    { "name": "River Navigation Department" }
]
